{   nombre: ["(UMSS) Universidad Mayor de San Simón",
    "(UMSA) Universidad Mayor de San Andrés",
    "(UCB) Universidad Católica Boliviana",
    "(USFX) Universidad Mayor de San Francisco Xavier",
    "(UPSA) Universidad Privada de Santa Cruz de la Sierra",
    "(UAGRM) Universidad Autónoma Gabriel René Moreno",
    "(UPB) Universidad Privada Boliviana",
    "(UNIVALLE) Universidad Privada del Valle",
    "(UDABOL) Universidad de Aquino Bolivia",
    "(UAJMS) Universidad Autónoma Juan Misael Saracho",
    "Universidad Nur",
    "(UASB) Universidad Andina Simón Bolivar",
    "(UTO) Universidad Técnica de Oruro",
    "(UPAL) Universidad Privada Abierta Latinoamericana",	
    "(UATF) Universidad Autónoma Tomás Frías",
    "(USALESIANA) Universidad Salesiana de Bolivia",
    "(UPDS) Universidad Privada Domingo Savio",
    "(EMI) Escuela Militar de Ingeniería",
    "(UTEPSA) Universidad Tecnológica Privada de Santa Cruz",
    "(UAB) Universidad Adventista de Bolivia",
    "Universidad Loyola",
    "(UNIFRANZ) Universidad Privada Franz Tamayo",
    "(UNSLP) Universidad Privada Nuestra Señora de La Paz",
    "(UNICEN) Universidad Central",
    "(UABJB) Universidad Autónoma del Beni José Ballivián",
    "(UTB) Universidad Tecnológica Boliviana",
    "(UNSXX) Universidad Nacional de Siglo XX",
    "(UEB) Universidad Evangélica Boliviana",
    "(UPEA) Universidad Pública de El Alto",	
    "(UECOLOGIA) Universidad Nacional Ecológica",	
    "(USFA) Universidad Privada San Francisco de Asís",	
    "(UCEBOL) Universidad Cristiana de Bolivia",	
    "(UAP) Universidad Amazónica de Pando",	
    "(UNITEPC) Universidad Técnica Privada Cosmos",	
    "(UCORDILLERA) Universidad de la Cordillera",
    "(ULS) Universidad La Salle",	
    "(UREAL) Universidad Real",	
    "(UPIEB) Universidad para la Investigación Estratégica en Bolivia",	 
    "(UDELOSANDES) Universidad de los Andes", 
    "(UNO) Universidad Nacional del Oriente", 
    "Universidad Privada Cumbre", 
    "(UCATEC) Universidad Privada de Ciencias Administrativas y Tecnológicas",
    "(USIP) Universidad Simón I. Patiño", 
    "(UDI) Universidad para el Desarrollo y la Innovación",	 
    "(UB) Universidad Unión Bolivariana", 
    "(UNIOR) Universidad Privada de Oruro",	 
    "(UNIBETH) Universidad Bethesda", 
    "(ULAT) Universidad Latinoamericana",	 
    "(UBI) Universidad Boliviana de Informática", 
    "Universidad Unidad",
    "(USP) Universidad Saint Paul"]

}